platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk-8}

inputs:
- name: spring-concourse-ci

outputs:
- name: build-out

run:
  path: spring-concourse-ci/ci/build.sh
