resources:
- name: source
  type: git
  source:
    uri: https://github.com/do-mas/spring-concourse-ci
    branch: master

- name: staging-app
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: domas.juodele@gmail.com
    password: Pivotal$1
    organization: doju-pro
    space: development

jobs:

- name: test-app
  plan:
  - get: source
    trigger: true
  - task: tests
    file: spring-concourse-ci/ci/build.yml
  - put: staging-app
    params:
      manifest: build-out/manifest.yml

